spring:
  application:
    name: eureka-server
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
    # fetch-registry: false
    # register-with-eureka: false
  instance:
    hostname: serve2
