spring:
  application:
    name: consumer-feign

server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8090/eureka/
  instance:
    prefer-ip-address: true
    instance-id: consumer-feign
