spring:
  application:
    name: consumer-hystrik

server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8090/eureka/
  instance:
    prefer-ip-address: true
    instance-id: consumer-hystrik