server:
  port: 7000
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8090/eureka/
zuul:
  routes:
    provider:
      path: /p/**
      serviceId: provider
    consumer:
      path: /c/**
      serviceId: consumer
  ignored-services:
    - provider

