spring:
  application:
    name: eureka-server
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka
    # register-with-eureka: false
    # fetch-registry: false
  instance:
    hostname: serve1