server:
  port: 9060
spring:
  application:
    name: provider
eureka:
  instance:
    prefer-ip-address: true
    instance-id: provider-2
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8090/eureka/
